// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UdemyClone.Domain.Database;

#nullable disable

namespace UdemyClone.Domain.Migrations
{
    [DbContext(typeof(UdemyCloneContext))]
    [Migration("20260528035808_InicializarEstadoActual")]
    partial class InicializarEstadoActual
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UdemyClone.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<int?>("CategoriaPadreId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaId");

                    b.HasIndex("CategoriaPadreId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CursoId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idioma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CursoId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.CursoInstructor", b =>
                {
                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.HasKey("CursoId", "InstructorId");

                    b.HasIndex("InstructorId");

                    b.ToTable("CursoInstructores");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.Estudiante", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstudianteId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstudianteId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.Inscripcion", b =>
                {
                    b.Property<int>("InscripcionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InscripcionId"));

                    b.Property<string>("CuponCodigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrecioPagado")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("InscripcionId");

                    b.HasIndex("CursoId");

                    b.HasIndex("EstudianteId", "CursoId")
                        .IsUnique();

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstructorId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Instructores");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.Leccion", b =>
                {
                    b.Property<int>("LeccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeccionId"));

                    b.Property<int>("DuracionSegundos")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("SeccionId")
                        .HasColumnType("int");

                    b.Property<int>("TipoLeccionId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeccionId");

                    b.HasIndex("SeccionId");

                    b.HasIndex("TipoLeccionId");

                    b.ToTable("Lecciones");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.ListaDeseo", b =>
                {
                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.HasKey("CursoId", "EstudianteId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("ListaDeseos");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.Progreso", b =>
                {
                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<int>("LeccionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaTerminada")
                        .HasColumnType("datetime2");

                    b.HasKey("EstudianteId", "LeccionId");

                    b.HasIndex("LeccionId");

                    b.ToTable("Progresos");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.Resena", b =>
                {
                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResenaTexto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Resena");

                    b.HasKey("EstudianteId", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("Resenas");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.Seccion", b =>
                {
                    b.Property<int>("SeccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeccionId"));

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeccionId");

                    b.HasIndex("CursoId");

                    b.ToTable("Secciones");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.TipoLeccion", b =>
                {
                    b.Property<int>("TipoLeccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoLeccionId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoLeccionId");

                    b.ToTable("TiposLeccion");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.Categoria", b =>
                {
                    b.HasOne("UdemyClone.Domain.Entities.Categoria", "CategoriaPadre")
                        .WithMany("Subcategorias")
                        .HasForeignKey("CategoriaPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaPadre");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.Curso", b =>
                {
                    b.HasOne("UdemyClone.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Cursos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.CursoInstructor", b =>
                {
                    b.HasOne("UdemyClone.Domain.Entities.Curso", "Curso")
                        .WithMany("CursoInstructores")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UdemyClone.Domain.Entities.Instructor", "Instructor")
                        .WithMany("CursoInstructores")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.Inscripcion", b =>
                {
                    b.HasOne("UdemyClone.Domain.Entities.Curso", "Curso")
                        .WithMany("Inscripciones")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UdemyClone.Domain.Entities.Estudiante", "Estudiante")
                        .WithMany("Inscripciones")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.Leccion", b =>
                {
                    b.HasOne("UdemyClone.Domain.Entities.Seccion", "Seccion")
                        .WithMany("Lecciones")
                        .HasForeignKey("SeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UdemyClone.Domain.Entities.TipoLeccion", "TipoLeccion")
                        .WithMany("Lecciones")
                        .HasForeignKey("TipoLeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seccion");

                    b.Navigation("TipoLeccion");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.ListaDeseo", b =>
                {
                    b.HasOne("UdemyClone.Domain.Entities.Curso", "Curso")
                        .WithMany("ListaDeseos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UdemyClone.Domain.Entities.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.Progreso", b =>
                {
                    b.HasOne("UdemyClone.Domain.Entities.Estudiante", "Estudiante")
                        .WithMany("Progresos")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UdemyClone.Domain.Entities.Leccion", "Leccion")
                        .WithMany("Progresos")
                        .HasForeignKey("LeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Leccion");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.Resena", b =>
                {
                    b.HasOne("UdemyClone.Domain.Entities.Curso", "Curso")
                        .WithMany("Resenas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UdemyClone.Domain.Entities.Estudiante", "Estudiante")
                        .WithMany("Resenas")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.Seccion", b =>
                {
                    b.HasOne("UdemyClone.Domain.Entities.Curso", "Curso")
                        .WithMany("Secciones")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Cursos");

                    b.Navigation("Subcategorias");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.Curso", b =>
                {
                    b.Navigation("CursoInstructores");

                    b.Navigation("Inscripciones");

                    b.Navigation("ListaDeseos");

                    b.Navigation("Resenas");

                    b.Navigation("Secciones");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.Estudiante", b =>
                {
                    b.Navigation("Inscripciones");

                    b.Navigation("Progresos");

                    b.Navigation("Resenas");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.Instructor", b =>
                {
                    b.Navigation("CursoInstructores");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.Leccion", b =>
                {
                    b.Navigation("Progresos");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.Seccion", b =>
                {
                    b.Navigation("Lecciones");
                });

            modelBuilder.Entity("UdemyClone.Domain.Entities.TipoLeccion", b =>
                {
                    b.Navigation("Lecciones");
                });
#pragma warning restore 612, 618
        }
    }
}
